### ISSUE TITLE
npm install ，出现[Vue warn]: Error when rendering component <mt-swipe>: warn  ReferenceError: _h is not defined

### ISSUE THREAD

**Issue by SidFeng** [ElemeFE/vue-swipe#32]
这是据说的解决方法，是不是你们要更新一下vue的版本http://stackoverflow.com/questions/41142784/node-dependency-stopped-working

**Comment by SidFeng** [comment]
我自己解决了，npm 包版本的问题
"vue": "2.1.3",
 "vue-template-compiler":"2.1.3",
"vue-loader": "10.0.0",
固定装这几个版本，就不会出问题了，执行下面的命令

sudo rm -rf node_modules
sudo npm cache clean
sudo cnpm install

**Comment by callect** [comment]
这不是根本的解决方法啊，这样VUE版本就不能升级了
