### ISSUE TITLE
Invalid prop: type check failed for prop "auto". Expected Number, got String.

### ISSUE THREAD

**Issue by drwpow** [ElemeFE/vue-swipe#33]
I get a `[Vue warn]` when I initialize the component like this:
```
<swipe auto="7000">

> [Vue warn]: Invalid prop: type check failed for prop "auto". Expected Number, got String. 
(found in component <mt-swipe>)
```
It seems to be parsing `7000` as a string, but for my purposes this is the simplest, most-straightforward way to configure this. Is there a better way to set this prop while keeping it as an attribute in the template?

**Comment by rico-ocepek** [comment]
That's not an issue of this plugin.

You have to use :attribute="value" when binding properties with type != String.

So in your case
`<swipe :auto="7000" />`

**Comment by drwpow** [comment]
You’re right—this is a Vue 2 warning and has nothing to do with this plugin specifically. It might be helpful to mention that in the docs (I swear I found that in an example somewhere…), but 100% extra and not necessary.
