### ISSUE TITLE
图片超大时，滑动图片可能会导致页面不必要的重绘

### ISSUE THREAD

**Issue by YongX** [ElemeFE/vue-swipe#41]
发现可滑动的区域，并没有单独提升为一个层。所以在图片超大的情况下，可能会导致页面产生不必要的重绘。

见下图：

![wechatimg43](https://cloud.githubusercontent.com/assets/7367678/23997369/06fc0776-0a8c-11e7-8ce9-739dcd4c6290.jpeg)

解决方法就是在 `.mint-swipe, .mint-swipe-items-wrap` 这里面将滑动区域整体提升为一个单独的层

**Comment by Leopoldthecoder** [comment]
Fixed in #42 🍷
