### ISSUE TITLE
 同步了 “add goto event” 更新后，index失效

### ISSUE THREAD

**Issue by zhenji** [ElemeFE/vue-swipe#55]
如题，同步后，当swipe时候，原本显示的白色标点不会改变，且执行goto event也不能跳转到指定index啊

**Comment by cloudfroster** [comment]
goto 是采用 $emit 调用的 详细参看 example。 index白色标点不会改变已修复。

**Comment by cloudfroster** [comment]
v2.2.0 采用 this.$refs.xxx.goto(index).
