### ISSUE TITLE
在轮播内横向滑动后再纵向滑动极长的距离，动画卡住

### ISSUE THREAD

**Issue by 791045873** [ElemeFE/vue-swipe#60]
RT

**Comment by cloudfroster** [comment]
请在 jsfiddle 提供下重现样板代码

**Comment by 791045873** [comment]
https://h5.ele.me/msite/
我用电脑打开ele移动端网站发现的，就是首页最上边的那个轮播。
您可以试一下，不知道github怎么贴gif，抱歉没法重现。

**Comment by cloudfroster** [comment]
并未重现 谢谢反馈 等提供重现代码后处理

**Comment by koucxz** [comment]
@cloudIC

![image](https://user-images.githubusercontent.com/24607191/39354050-0030f8ca-4a3c-11e8-9741-e615ecb449f0.png)

只要横向滑动再纵向滑动就会卡住
安卓移动端，腾讯X5、Chrome都能重现
