### ISSUE TITLE
兼容性bug

### ISSUE THREAD

**Issue by mlboy** [ElemeFE/vue-swipe#8]
部分手机中 不能滑动
部分手机中不能自动切换
部分手机中点击会出现闪动

**Comment by furybean** [comment]
不能滑动的问题：可以通过设置 prevent 属性为 true 来解决。
其他两个不清楚如何重现，请告知重现条件。

**Comment by mlboy** [comment]
非常感谢,解决了不能滑动问题.

点击闪现那个问题是chrome 33 时候渲染的bug

.swipe-items-wrap > div {
    position: absolute;
    -webkit-transform: translateX(100%);
    transform: translateX(100%);
    width: 100%;
    height: 100%;
    display: none;
}
.swipe-items-wrap > div.active {
    -webkit-transform-style: preserve-3d;
    -webkit-transform: translate3d(0,0,0);
    transform: translate3d(0,0,0);
    display: block;

增加了几个属性 好了
