### ISSUE TITLE
不能增加事件

### ISSUE THREAD

**Issue by mlboy** [ElemeFE/vue-swipe#9]
不能增加 <swipe-item @click="alert()"

**Comment by furybean** [comment]
可以试试 @tap。

**Comment by mlboy** [comment]
可以加你q讨论下吗, 415235169

**Comment by mlboy** [comment]
是因为
https://github.com/ElemeFE/vue-swipe/issues/8#issuecomment-191042599
导致的, prevent = true时候就不能触发事件了

**Comment by furybean** [comment]
是的，所以我加了自定义事件 @tap 来解决这个问题。你把 @click 换成 @tap 就可以了。

**Comment by iqingting** [comment]
click 和 tap 表示无缘无故被 @ 了好几次
